#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  #  端口
  port: 8888
spring:
  application:
    name: manager
  datasource:
    url: jdbc:mysql://47.107.165.252:3306/ler
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.manager.entity
  config-locatins: classpath:/mybatis/mybatis-config.xml
