#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  #  端口
  port: 8888
spring:
  application:
    name: manager
  datasource:
    url: jdbc:oracle:thin:@//110.185.100.222:1521/SYSTEMTEST
    username: SYSTEMTEST
    password: SYSTEMTEST
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dbcp2:
      max-idle: 10
    tomcat:
      max-wait: 10000
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.lerh.entity
  config-locatins: classpath:/mybatis/mybatis-config.xml
